#!/bin/bash

APP_MODULE="app.main:app"   # Change this to your FastAPI app module
HOST="127.0.0.1"              # Host to listen on
PORT="8080"                 # Port to listen on
WORKERS="4"                 # Number of Uvicorn worker processes


# ONLY Uncomment one of the below.

# Uncomment below if you feel that no need to log from the application itself
# --forwarded-allow-ips is restricted to the local reverse proxy (this script binds to
# 127.0.0.1 only) - never use '*' here, or any client could spoof X-Forwarded-For/X-Real-IP.
#/opt/cratos-fastapi/.venv/bin/uvicorn ${APP_MODULE} --host ${HOST} --port ${PORT} --workers ${WORKERS} --no-server-header --proxy-headers --forwarded-allow-ips='127.0.0.1'
